<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
//$APPLICATION->SetAdditionalCSS(SITE_TEMPLATE_PATH.'/about.css');
$APPLICATION->SetTitle("Специальные предложения");

global $SORT;
global $ORDER;

$SORT = $_GET['sort'] ?? 'shows';
$ORDER = $_GET['order'] ?? 'asc';
?><?$APPLICATION->IncludeComponent(
    "bitrix:sale.bestsellers",
    "popular_products_page",
    Array(
        "ACTION_VARIABLE" => "action",
        "ADDITIONAL_PICT_PROP_12" => "",
        "ADDITIONAL_PICT_PROP_13" => "",
        "ADDITIONAL_PICT_PROP_21" => "MORE_PHOTO",
        "ADDITIONAL_PICT_PROP_22" => "MORE_PHOTO",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "BASKET_URL" => "/personal/basket.php",
        "BY" => "AMOUNT",
        "CACHE_TIME" => "86400",
        "CACHE_TYPE" => "A",
        "CART_PROPERTIES_12" => array("",""),
        "CART_PROPERTIES_13" => array("",""),
        "CART_PROPERTIES_21" => array("SHIRINA_PAZA",""),
        "CART_PROPERTIES_22" => array("CML2_MANUFACTURER",""),
        "CONVERT_CURRENCY" => "N",
        "DETAIL_URL" => "",
        "DISPLAY_COMPARE" => "N",
        "FILTER" => array("CANCELED","ALLOW_DELIVERY","PAYED","DEDUCTED","N","O","P","F"),
        "HIDE_NOT_AVAILABLE" => "Y",
        "LABEL_PROP_12" => "-",
        "LABEL_PROP_21" => "-",
        "LINE_ELEMENT_COUNT" => "3",
        "MESS_BTN_BUY" => "Купить",
        "MESS_BTN_DETAIL" => "Подробнее",
        "MESS_BTN_SUBSCRIBE" => "Подписаться",
        "MESS_NOT_AVAILABLE" => "Нет в наличии",
        "OFFER_TREE_PROPS_13" => array(),
        "OFFER_TREE_PROPS_22" => array("CML2_MANUFACTURER"),
        "PAGE_ELEMENT_COUNT" => "3000",
        "PARTIAL_PRODUCT_PROPERTIES" => "Y",
        "PERIOD" => "40",
        "PRICE_CODE" => array("BASE","Оптовая руб","Розничная руб."),
        "PRICE_VAT_INCLUDE" => "Y",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "quantity",
        "PRODUCT_SUBSCRIPTION" => "N",
        "PROPERTY_CODE_12" => array("",""),
        "PROPERTY_CODE_13" => array("",""),
        "PROPERTY_CODE_21" => array("TSVET_","SHIRINA_PAZA","TIP_OTDELKI","TIP_POLOTNA","PROIZVODITEL","BLOG_POST_ID","CML2_ARTICLE","CML2_BASE_UNIT","MORE_PHOTO","BLOG_COMMENTS_CNT","CML2_MANUFACTURER","SALE","CML2_TRAITS","CML2_TAXES","FILES","FASOVKA","CML2_ATTRIBUTES","CML2_BAR_CODE","NAZNACHENIE","MODEL","STEKLO","MOSHCHNOST","OBEM_BARABANA","TIP_DVIGATELYA","VENETS","KONSTRUKTSIYA","TSVET","STEPEN_BLESKA","TIP","TORGOVAYA_MARKA","VREMYA_VYSYKHANIYA","OBEM_VES","SEZONNOST","VID","PRIMENENIE","VES","VYSOTA","STRANA_PROIZVODITEL_","TOLSHCHINA","MATERIAL","GLUBINA","TSVETOVOY_TON","RAZMER","KLASS_IZNOSOSTOYKOSTI","KOLLEKTSIYA","KV_METROV_V_UPAKOVKE","KOLICHESTVO_V_UPAKOVKE","RAZMER_DOSKI","FASKA","OTTENOK","POVERKHNOST_DOSKI","TIP_DIZAYNA","TIP_SOEDINENIYA_","RASKHOD","RASTVORITEL_","OBLAST_PRIMENENIYA","SPOSOB_NANESENIYA","TIP_VNESHNEY_OTDELKI","TIP_VNUTRENNEY_OTDELKI","TSVET_VNESHNEY_OTDELKI","TSVET_VNUTRENNEY_OTDELKI","OSNOVA","DLINA","RAZMER_YACHEYKI","PLOSHCHAD_LISTA_M2","MARKA_PROCHNOSTI","RAZMER_ZAKLEPOK","DIAMETR","ZERNISTOST","NAPRYAZHENIE","SHIRINA","PLOSHCHAD_M2","OSOBENNOSTI","POKRYTIE","KOLLICHESTVO_SEKTSIY","KOLLICHESTVO_STUPENEY_V_SEKTSII","MAKSIMALNAYA_NAGRUZKA","PITANIE","PATRON","SKOROST_VRASHCHENIYA","DIAMETR_DISKA","CHASTOTA_UDAROV","RABOCHAYA_TEMPERATURA","RAZMER_LENTY","VKHODNOE_NAPRYAZHENIE","VYKHODNOE_NAPRYAZHENIE","FORMA","STIL","TIP_TSOKOLYA","KOLLICHESTVO_LAMP","TIP_LAMPY","OBYEM_BAKA","PROIZVODITELNOST","UGOL","PODKLYUCHENIE","IZLIV","NOMINALNYY_TOK_A","KOLLICHESTVO_POLYUSOV","NOMINALNAYA_OTKLYUCHAYUSHCHAYA_SPOSOBNOST_KA","CHASTOTA","KOLICHESTVO_PROVODOV_SHT","SECHENIE_MM2","KATEGORIYA","FORMA_PODDONA","SKIDKA","PODDON","STARAYA_TSENA","NALICHIE_KRYSHI","STEKLO_MM","GIDROMASSAZH","NALICHIE_PODSVETKI","NALICHIE_POLKI","TIP_SLIVA","PODVOD_VODY","MATERIAL_BAKA","GARANTIYA_LET","EMKOST_L","RASKHOD_GORYACHEY_VODY_L_MIN","TIP_PODVODKI","OTKRYVANIE","TIP_VENTILYA","POLOTNO","NOMINALNAYA_MOSHCHNOST","MAKSIMALNAYA_MOSHCHNOST","OBEM_TOPLIVNOGO_BAKA","UROVEN_SHUMA","ENERGIYA_UDARA","KOLICHESTVO_SKOROSTEY","DIAMETR_PATRONA","MAKSIMALNYY_KRUTYASHCHIY_MOMENT","CHASTOTA_KHODA","TOCHNOST_IZMERENIYA","TOCHNOST_IZERENIYA","DALNOST_IZMERENIYA","KOLICHESTVO_LUCHEY","SKOROST_LENTY","LENTA","KOLICHESTVO_KOLES","KOLICHESTVO_NOZHEY","KOLICHESTVO_PREDMETOV","OBEM","RAZMER_POSADKI","RAZMER_GOLOVKI","OBEM_TOPLIVA","UTSENKA","PLOTNOST","PRICHINA_UTSENKI",""),
        "PROPERTY_CODE_22" => array("",""),
        "SHOW_DISCOUNT_PERCENT" => "Y",
        "SHOW_IMAGE" => "Y",
        "SHOW_NAME" => "Y",
        "SHOW_OLD_PRICE" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "SHOW_PRODUCTS_12" => "N",
        "SHOW_PRODUCTS_21" => "Y",
        "TEMPLATE_THEME" => "blue",
        "USE_PRODUCT_QUANTITY" => "Y",
    )
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>